CREATE TABLE IF NOT EXISTS `#__doors` (
`id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT,

`name` VARCHAR(200)  NOT NULL ,

`ref` VARCHAR(8)  NOT NULL ,
`ean13` BIGINT(13) ,
`upc` BIGINT(13) ,
`hs_code` BIGINT(8) ,

`family` VARCHAR(100)  NOT NULL ,
`width` FLOAT(8,2)  NOT NULL ,
`height` FLOAT(8,2)  NOT NULL ,
`number_of_doors` VARCHAR(255)  NOT NULL ,
`gross_weight` FLOAT(8,2)  NOT NULL ,
`finish` VARCHAR(255)  NOT NULL ,
`fire_resistance` INT(3)  NOT NULL ,
`rw` INT(3)  NOT NULL ,
`dnfw` INT(3)  NOT NULL ,

`outer_width` FLOAT(8,2)  NOT NULL ,
`outer_height` FLOAT(8,2)  NOT NULL ,
`recommended_construction_width` FLOAT(8,2)  NOT NULL ,
`recommended_construction_height` FLOAT(8,2)  NOT NULL ,

`units_per_pallet` INT(2)  NOT NULL ,
`pallet_length` FLOAT(8,2)  NOT NULL ,
`pallet_width` FLOAT(8,2)  NOT NULL ,
`pallet_height` FLOAT(8,2)  NOT NULL ,
`pallet_volume` FLOAT(8,2)  NOT NULL ,
`pallet_weight` FLOAT(8,2)  NOT NULL ,
`msrp` FLOAT(7,2)  NOT NULL ,
`msrp_state` TINYINT(1)  NOT NULL DEFAULT '1',

`keylock` VARCHAR(255)  NOT NULL ,
`keylock_ref` VARCHAR(10)  NOT NULL ,
`keylock_msrp` FLOAT(7,2)  NOT NULL ,
`antipanic_bar` VARCHAR(255)  NOT NULL ,
`antipanic_bar_ref` VARCHAR(10)  NOT NULL ,
`antipanic_bar_msrp` FLOAT(7,2)  NOT NULL ,
`keylock_antipanicbar_ref` VARCHAR(10)  NOT NULL ,
`keylock_antipanicbar_msrp` FLOAT(7,2)  NOT NULL ,
`circular_double_window` VARCHAR(255)  NOT NULL ,
`circular_double_window_ref` VARCHAR(10)  NOT NULL ,
`circular_double_window_msrp` FLOAT(7,2)  NOT NULL ,
`without_floor_frame` VARCHAR(255)  NOT NULL ,
`without_floor_frame_ref` VARCHAR(10)  NOT NULL ,
`without_floor_frame_msrp` FLOAT(7,2)  NOT NULL ,
`autoclose_system` VARCHAR(255)  NOT NULL ,
`autoclose_system_ref` VARCHAR(10)  NOT NULL ,
`autoclose_system_msrp` FLOAT(7,2)  NOT NULL ,

`description1` TEXT NOT NULL ,
`description2` TEXT NOT NULL ,

`catalog_page` VARCHAR(255)  NOT NULL ,
`installation_manual` VARCHAR(255)  NOT NULL ,
`sketchup` VARCHAR(255)  NOT NULL ,
`warranty` VARCHAR(255)  NOT NULL ,
`drawings` VARCHAR(255)  NOT NULL ,
`safety_data` VARCHAR(255)  NOT NULL ,
`acoustic_report` VARCHAR(255)  NOT NULL ,

`video` VARCHAR(255)  NOT NULL ,
`photo_150px` VARCHAR(255)  NOT NULL ,
`photo_300px` VARCHAR(255)  NOT NULL ,
`photo_1024px` VARCHAR(255)  NOT NULL ,
`photo_detail1` VARCHAR(255)  NOT NULL ,
`photo_detail2` VARCHAR(255)  NOT NULL ,
`photo_detail3` VARCHAR(255)  NOT NULL ,
`photo_detail4` VARCHAR(255)  NOT NULL ,
`photo_detail5` VARCHAR(255)  NOT NULL ,
`portfolio_photo_id1` int(11) UNSIGNED NOT NULL,
`portfolio_photo_id2` int(11) UNSIGNED NOT NULL,

`music_broadcast` TINYINT(1)  NOT NULL DEFAULT '1',
`hifi_home_cinema` TINYINT(1)  NOT NULL DEFAULT '1',
`building_construction` TINYINT(1)  NOT NULL DEFAULT '1',

`state` TINYINT(1)  NOT NULL DEFAULT '1',
`state_featured` TINYINT(1)  NOT NULL ,
`created_by` INT(11)  NOT NULL ,
PRIMARY KEY (`id`)
) DEFAULT COLLATE=utf8_general_ci;

