CREATE TABLE IF NOT EXISTS `#__panels` (
`id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT,

`name` VARCHAR(200)  NOT NULL ,
`ref` VARCHAR(200)  NOT NULL ,
`ean13` BIGINT(13) ,
`hs_code` BIGINT(8) ,

`family` VARCHAR(200)  NOT NULL ,
`length` FLOAT(6,1)  NOT NULL ,
`width` FLOAT(6,1)  NOT NULL ,
`diameter` FLOAT(6,1)  NOT NULL ,
`thickness` FLOAT(6,1)  NOT NULL ,
`weight` FLOAT(6,2)  NOT NULL ,
`load_weight` FLOAT(6,2)  NOT NULL ,
`density` DECIMAL(6,3)  NOT NULL ,

`absorption_class` VARCHAR(255)  NOT NULL ,
`aw` VARCHAR(255)  NOT NULL ,
`nrc` FLOAT(6,3)  NOT NULL ,
`absorption_class_2` VARCHAR(255)  NOT NULL ,
`aw_2` VARCHAR(255)  NOT NULL ,
`nrc_2` FLOAT(6,3)  NOT NULL ,
`light_reflection` FLOAT(4,1)  NOT NULL ,
`humidity_resistance` FLOAT(4,1)  NOT NULL ,
`thermal_conductivity` FLOAT(6,2)  NOT NULL ,
`absorption_frequency` VARCHAR(255)  NOT NULL ,

`fire_class_en` VARCHAR(40)  NOT NULL ,
`fire_class_din` VARCHAR(40)  NOT NULL ,
`fire_class_nf_p` VARCHAR(40)  NOT NULL ,
`fire_class_uni` VARCHAR(40)  NOT NULL ,
`fire_class_bs` VARCHAR(40)  NOT NULL ,
`humidity_class` INT(4)  NOT NULL ,

`functionality` VARCHAR(255)  NOT NULL ,
`installation_wall` VARCHAR(255)  NOT NULL ,
`installation_ceiling` VARCHAR(255)  NOT NULL ,
`installation_vas` VARCHAR(255)  NOT NULL ,
`installation_floor` VARCHAR(255)  NOT NULL ,
`installation_corner` VARCHAR(255)  NOT NULL ,
`fixing_type_standard15` VARCHAR(255)  NOT NULL ,
`fixing_type_standard24` VARCHAR(255)  NOT NULL ,
`fixing_type_clipin` VARCHAR(255)  NOT NULL ,
`fixing_type_screwed` VARCHAR(255)  NOT NULL ,
`fixing_type_glued` VARCHAR(255)  NOT NULL ,
`fixing_type_adhesive` VARCHAR(255)  NOT NULL ,

`wood` VARCHAR(255)  NOT NULL ,
`metal` VARCHAR(255)  NOT NULL ,
`fabric` VARCHAR(255)  NOT NULL ,
`foam` VARCHAR(255)  NOT NULL ,
`polystyrene` VARCHAR(255)  NOT NULL ,

`wood_color` VARCHAR(255)  NOT NULL ,
`wood_type` VARCHAR(255)  NOT NULL ,
`metal_color` VARCHAR(255)  NOT NULL ,
`fabric_color` VARCHAR(255)  NOT NULL ,
`fabric_type` VARCHAR(255)  NOT NULL ,
`foam_type` VARCHAR(255)  NOT NULL ,
`polystyrene_color` VARCHAR(255)  NOT NULL ,
`polystyrene_density` FLOAT(4,1)  NOT NULL ,
`edge_leveled` VARCHAR(255)  NOT NULL ,
`edge_angled` VARCHAR(255)  NOT NULL ,
`scratch_resistance` VARCHAR(255)  NOT NULL ,
`washable` VARCHAR(255)  NOT NULL ,
`recycle_coefficient` FLOAT(4,1)  NOT NULL ,

`units_per_box` VARCHAR(50)  NOT NULL ,
`box_length` FLOAT(5,1)  NOT NULL ,
`box_width` FLOAT(5,1)  NOT NULL ,
`box_height` FLOAT(5,1)  NOT NULL ,
`box_weight` DECIMAL(5,1)  NOT NULL ,
`box_volume` DECIMAL(6,3)  NOT NULL ,
`box_msrp` FLOAT(5,1)  NOT NULL ,
`mastercarton_box_length` FLOAT(5,1)  NOT NULL ,
`mastercarton_box_width` FLOAT(5,1)  NOT NULL ,
`mastercarton_box_height` FLOAT(5,1)  NOT NULL ,
`mastercarton_box_msrp` FLOAT(5,1)  NOT NULL ,

`description1` TEXT NOT NULL ,
`description2` TEXT NOT NULL ,

`catalog_page` VARCHAR(255)  NOT NULL ,
`installation_manual` VARCHAR(255)  NOT NULL ,
`sketchup` VARCHAR(255)  NOT NULL ,
`warranty` VARCHAR(255)  NOT NULL ,
`drawings` VARCHAR(255)  NOT NULL ,
`safety_data` VARCHAR(255)  NOT NULL ,
`acoustic_report` VARCHAR(255)  NOT NULL ,

`video` VARCHAR(255)  NOT NULL ,
`photo_row_material` VARCHAR(255)  NOT NULL ,
`photo_150px` VARCHAR(255)  NOT NULL ,
`photo_300px` VARCHAR(255)  NOT NULL ,
`photo_1024px` VARCHAR(255)  NOT NULL ,
`photo_detail1` VARCHAR(255)  NOT NULL ,
`photo_detail2` VARCHAR(255)  NOT NULL ,
`photo_detail3` VARCHAR(255)  NOT NULL ,
`photo_detail4` VARCHAR(255)  NOT NULL ,
`photo_detail5` VARCHAR(255)  NOT NULL ,
`portfolio_photo_id1` int(11) UNSIGNED NOT NULL,
`portfolio_photo_id2` int(11) UNSIGNED NOT NULL,
`portfolio_photo_id3` int(11) UNSIGNED NOT NULL,

`graph_id` int(11) UNSIGNED NOT NULL,

`music_broadcast` TINYINT(1)  NOT NULL DEFAULT '1',
`hifi_home_cinema` TINYINT(1)  NOT NULL DEFAULT '1',
`building_construction` TINYINT(1)  NOT NULL DEFAULT '1',

`state` TINYINT(1)  NOT NULL DEFAULT '1',
`state_featured` TINYINT(1)  NOT NULL ,
`created_by` INT(11)  NOT NULL ,
PRIMARY KEY (`id`)
) DEFAULT COLLATE=utf8_general_ci;


CREATE TABLE IF NOT EXISTS `#__panel_graphs` (
`id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT,

`label` VARCHAR(140)  NOT NULL ,
`graph_63hz` FLOAT(3,2) ,
`graph_80hz` FLOAT(3,2) DEFAULT NULL,
`graph_100hz` FLOAT(3,2) DEFAULT NULL,
`graph_125hz` FLOAT(3,2) DEFAULT NULL,
`graph_160hz` FLOAT(3,2) DEFAULT NULL,
`graph_200hz` FLOAT(3,2) DEFAULT NULL,
`graph_250hz` FLOAT(3,2) DEFAULT NULL,
`graph_315hz` FLOAT(3,2) DEFAULT NULL,
`graph_400hz` FLOAT(3,2) DEFAULT NULL,
`graph_500hz` FLOAT(3,2) DEFAULT NULL,
`graph_630hz` FLOAT(3,2) DEFAULT NULL,
`graph_800hz` FLOAT(3,2) DEFAULT NULL,
`graph_1000hz` FLOAT(3,2) DEFAULT NULL,
`graph_1250hz` FLOAT(3,2) DEFAULT NULL,
`graph_1600hz` FLOAT(3,2) DEFAULT NULL,
`graph_2000hz` FLOAT(3,2) DEFAULT NULL,
`graph_2500hz` FLOAT(3,2) DEFAULT NULL,
`graph_3150hz` FLOAT(3,2) DEFAULT NULL,
`graph_4000hz` FLOAT(3,2) DEFAULT NULL,
`graph_5000hz` FLOAT(3,2) DEFAULT NULL,
`state` TINYINT(1)  NOT NULL DEFAULT '1',
`created_by` INT(11)  NOT NULL ,
PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT COLLATE=utf8_general_ci;
